### ISSUE TITLE
No cells identified

### ISSUE THREAD

**Issue by akatav** [hochbaumGroup/HNCcorr#2]
Hello,
thanks for writing this library. i am a newcomer in Ca imaging analysis. I used your library on 1 .avi file after after building the HNCCorr Movie() with the .avi file's data. But no cells are identified when HCCCorr.segment(movie) is called. What are some possible issues with the data or code leading to this?

**Comment by quic0** [comment]
Thanks for trying it and sorry for the slow response! I hadn't seen the issue. Unfortunately, I don't have enough information to give you any advice. Can you run the example correctly?

Also, the CaImAn library is more actively used (https://github.com/flatironinstitute/CaImAn)
