### ISSUE TITLE
On Direction of Feature Vectors: Rows or Columns?

### ISSUE THREAD

**Issue by wenxuanliang** [hochbaumGroup/HNCcorr#6]
Hi, I have a question regarding parameters s.percRows and s.percCols.
In function _approximatePCA_, the full correlation matrix (which should be symmetric) is downsampled to nRows x nCols (line 38), and then PCA analysis (line 41) is carried out with the each column treated as a variable (according to MATLAB document), and the resultant top _nComps_ PCA coefficient vectors are used to get PCA scores for all pixels (line 45-47).
In this sense, each row of the downsampled correlation matrix is a "feature vector" of a corresponding pixel as mentioned in the eNeuro paper, or equivalently, pixels corresponding to those columns are the smaller-size reference set. So we should have nCols < nRows.

However, in the class definition file _Solution.m_, we see:
            obj.percRows = 0.01;
            obj.percCols = 1;   
This seems to contradict the analysis above. Have I misundertood or missed something in the code?
Thank you!

**Comment by quic0** [comment]
Hi, your analysis is right but is does not lead to a contradiction. 

There are two types of sampling:
- There is the sampling of the reference set. As you point out, the feature vectors are rows of the correlation matrix and the reference set is a sampling of the columns of the correlation matrix. As you point out, this implies that the number of feature vectors is larger than the number of features in each vector.
- There is also sampling inside approximate PCA. Approximate PCA is only used to select the edges of the similarity graph. percRows and percCols are parameters of the approximate PCA implementation. percRows determines what fraction of the pixels we should use for the PCA analysis. percCol determines the fraction of entries in the feature vectors of the pixels that are used (we use all).

Combining both, then we sample both the number of feature vectors (approx PCA sampling) and the length of feature vector (reference set sampling). However, there is no contradiction.

Hope that helps.

**Comment by wenxuanliang** [comment]
Dear Dr. Spaen,

Thank you for your response!
I think we are on the same page about how the sampling is performed. I should not have described it as a "contradiation"; sorry for this.
The particular point about which I am inconfident is that typically when we perform PCA, we would hope we have more samples (number of rows here) than the number of variables (i.e. the dimension of feature space, or the number of columns here). So to keep all columns in _ApproximatePCA.m_ surprised me a little in the first place, especially since the eNeuro paper also mentioned the size of reference set is ~40% of total pixels in a given patch. But if I guess it could just work this way.

Learnt a lot from your code and paper. Thank you again and stay safe~


Best,
Wenxuan

**Comment by quic0** [comment]
Hi Wenxuan,

Thanks for your comments.
Regarding PCA, it does not require more samples than features. It is commonly used to reduce the number of features when the number of samples is small.
