### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by unbelievetable** [hochbaumGroup/HNCcorr#9]
Hi,

First thank you for this package! When I ran the given example, I encountered the error "Negative capacity for lambda equal to -0.000000. Set roundNegativeCapacity to 1 if the value should be rounded to 0." I simply copy and paste the code [here](https://github.com/hochbaumGroup/HNCcorr#example-python) and run.

**Comment by quic0** [comment]
Hi, 
You're welcome!
Could you check the version of the packages: hnccorr, closure-problem, and pseudoflow? You can do this with the `pip freeze` command. A previous fix should have fixed the bug.

**Comment by unbelievetable** [comment]
They are 
hnccorr == 2019.7.1
closure-problem == 2019.6.3
pseudoflow == 2019.8.3
I will make sure to update

One more thing is about the method under Movie.from_tiff_images. What exactly does the subsample parameter mean? The documentation says that it is the number of frames to average into a single frame, but isn't each image file represents a single frame?

**Comment by unbelievetable** [comment]
Unfortunately, I have the following problem when installing pseudoflow.

Running setup.py install for pseudoflow ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\UnbelieveTable\\AppData\\Local\\Temp\\pip-install-5vo1tgcv\\pseudoflow\\setup.py'"'"'; __file__='"'"'C:\\Users\\UnbelieveTable\\AppData\\Local\\Temp\\pip-install-5vo1tgcv\\pseudoflow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\UnbelieveTable\AppData\Local\Temp\pip-record-glv1vuvs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\pseudoflow'
         cwd: C:\Users\UnbelieveTable\AppData\Local\Temp\pip-install-5vo1tgcv\pseudoflow\
    Complete output (33 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\pseudoflow
    copying src\pseudoflow\__init__.py -> build\lib.win32-3.8\pseudoflow
    creating build\lib.win32-3.8\pseudoflow\python
    copying src\pseudoflow\python\hpf.py -> build\lib.win32-3.8\pseudoflow\python
    copying src\pseudoflow\python\__init__.py -> build\lib.win32-3.8\pseudoflow\python
    running build_ext
    building 'pseudoflow.libhpf' extension
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    creating build\temp.win32-3.8\Release\src
    creating build\temp.win32-3.8\Release\src\pseudoflow
    creating build\temp.win32-3.8\Release\src\pseudoflow\core
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python38-32\include" "-Ic:\program files (x86)\python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/pseudoflow/core/libhpf.c /Fobuild\temp.win32-3.8\Release\src/pseudoflow/core/libhpf.obj -std=c99 -O3
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    libhpf.c
    src/pseudoflow/core/libhpf.c(233): error C2059: syntax error: '<parameter-list>'
    src/pseudoflow/core/libhpf.c(240): error C2059: syntax error: '<parameter-list>'
    src/pseudoflow/core/libhpf.c(494): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(507): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1272): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1278): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1288): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1369): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2014): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2025): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2042): warning C4018: '<': signed/unsigned mismatch
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\UnbelieveTable\\AppData\\Local\\Temp\\pip-install-5vo1tgcv\\pseudoflow\\setup.py'"'"'; __file__='"'"'C:\\Users\\UnbelieveTable\\AppData\\Local\\Temp\\pip-install-5vo1tgcv\\pseudoflow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\UnbelieveTable\AppData\Local\Temp\pip-record-glv1vuvs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files (x86)\python38-32\Include\pseudoflow' Check the logs for full command output.

**Comment by quic0** [comment]
Ok, please update hnccorr to the latest version (2020.5.1). That should fix the bug.
Each image is a single frame, but when loading the tiffs the algorithm will average every "subsample" number of frames into one frame. You can set subsample to 1 to disable it.

**Comment by quic0** [comment]
You shouldn't need to install the pseudoflow package separately. You can use pip. Meanwhile, let me debug the pseudoflow issue.

**Comment by unbelievetable** [comment]
> You shouldn't need to install the pseudoflow package separately. You can use pip. Meanwhile, let me debug the pseudoflow issue.

Actually the same problem rises while using pip install hnccorr. Thanks for your time and effort!

**Comment by unbelievetable** [comment]
The complete log is the following `Collecting hnccorr
  Using cached hnccorr-2020.5.1-py3-none-any.whl (31 kB)
Requirement already satisfied: six in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (1.15.0)
Requirement already satisfied: numpy in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (1.18.5)
Requirement already satisfied: networkx in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (2.4)
Requirement already satisfied: pillow in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (7.1.2)
Requirement already satisfied: tqdm in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (4.46.1)
Collecting closure-problem>=2020.5.1
  Using cached closure_problem-2020.5.2-py3-none-any.whl (3.9 kB)
Requirement already satisfied: scipy in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (1.4.1)
Requirement already satisfied: sparsecomputation in c:\users\wesit\appdata\roaming\python\python38\site-packages (from hnccorr) (2019.6.3)
Requirement already satisfied: decorator>=4.3.0 in c:\users\wesit\appdata\roaming\python\python38\site-packages (from networkx->hnccorr) (4.4.2)
Collecting pseudoflow>=2020.5.1
  Using cached pseudoflow-2020.5.1.tar.gz (72 kB)
Requirement already satisfied: sklearn in c:\users\wesit\appdata\roaming\python\python38\site-packages (from sparsecomputation->hnccorr) (0.0)
Requirement already satisfied: scikit-learn in c:\users\wesit\appdata\roaming\python\python38\site-packages (from sklearn->sparsecomputation->hnccorr) (0.23.1)
Requirement already satisfied: joblib>=0.11 in c:\users\wesit\appdata\roaming\python\python38\site-packages (from scikit-learn->sklearn->sparsecomputation->hnccorr) (0.15.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\wesit\appdata\roaming\python\python38\site-packages (from scikit-learn->sklearn->sparsecomputation->hnccorr) (2.1.0)
Building wheels for collected packages: pseudoflow
  Building wheel for pseudoflow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\wesit\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"'; __file__='"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\wesit\AppData\Local\Temp\pip-wheel-470kae1i'
       cwd: C:\Users\wesit\AppData\Local\Temp\pip-install-inf_1mbl\pseudoflow\
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pseudoflow
  copying src\pseudoflow\__init__.py -> build\lib.win-amd64-3.8\pseudoflow
  creating build\lib.win-amd64-3.8\pseudoflow\python
  copying src\pseudoflow\python\hpf.py -> build\lib.win-amd64-3.8\pseudoflow\python
  copying src\pseudoflow\python\__init__.py -> build\lib.win-amd64-3.8\pseudoflow\python
  running build_ext
  building 'pseudoflow.libhpf' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\pseudoflow
  creating build\temp.win-amd64-3.8\Release\src\pseudoflow\core
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/pseudoflow/core/libhpf.c /Fobuild\temp.win-amd64-3.8\Release\src/pseudoflow/core/libhpf.obj -std=c99 -O3
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  libhpf.c
  src/pseudoflow/core/libhpf.c(233): error C2059: syntax error: '<parameter-list>'
  src/pseudoflow/core/libhpf.c(240): error C2059: syntax error: '<parameter-list>'
  src/pseudoflow/core/libhpf.c(494): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(507): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(1272): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(1278): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(1288): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(1369): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(2014): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(2025): warning C4018: '<': signed/unsigned mismatch
  src/pseudoflow/core/libhpf.c(2042): warning C4018: '<': signed/unsigned mismatch
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pseudoflow
  Running setup.py clean for pseudoflow
Failed to build pseudoflow
Installing collected packages: pseudoflow, closure-problem, hnccorr
    Running setup.py install for pseudoflow ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\wesit\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"'; __file__='"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\wesit\AppData\Local\Temp\pip-record-281pq1np\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\wesit\AppData\Roaming\Python\Python38\Include\pseudoflow'
         cwd: C:\Users\wesit\AppData\Local\Temp\pip-install-inf_1mbl\pseudoflow\
    Complete output (33 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pseudoflow
    copying src\pseudoflow\__init__.py -> build\lib.win-amd64-3.8\pseudoflow
    creating build\lib.win-amd64-3.8\pseudoflow\python
    copying src\pseudoflow\python\hpf.py -> build\lib.win-amd64-3.8\pseudoflow\python
    copying src\pseudoflow\python\__init__.py -> build\lib.win-amd64-3.8\pseudoflow\python
    running build_ext
    building 'pseudoflow.libhpf' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\pseudoflow
    creating build\temp.win-amd64-3.8\Release\src\pseudoflow\core
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/pseudoflow/core/libhpf.c /Fobuild\temp.win-amd64-3.8\Release\src/pseudoflow/core/libhpf.obj -std=c99 -O3
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    libhpf.c
    src/pseudoflow/core/libhpf.c(233): error C2059: syntax error: '<parameter-list>'
    src/pseudoflow/core/libhpf.c(240): error C2059: syntax error: '<parameter-list>'
    src/pseudoflow/core/libhpf.c(494): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(507): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1272): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1278): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1288): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(1369): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2014): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2025): warning C4018: '<': signed/unsigned mismatch
    src/pseudoflow/core/libhpf.c(2042): warning C4018: '<': signed/unsigned mismatch
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\wesit\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"'; __file__='"'"'C:\\Users\\wesit\\AppData\\Local\\Temp\\pip-install-inf_1mbl\\pseudoflow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\wesit\AppData\Local\Temp\pip-record-281pq1np\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\wesit\AppData\Roaming\Python\Python38\Include\pseudoflow' Check the logs for full command output.`

**Comment by quic0** [comment]
Thanks, there is likely a compilation issue for windows. I'll fix it in the next couple days and release a pre-build wheel.

**Comment by unbelievetable** [comment]
> Thanks, there is likely a compilation issue for windows. I'll fix it in the next couple days and release a pre-build wheel.

Great! Appreciate your work!!

**Comment by quic0** [comment]
Here is a quick-fix for the pseudoflow package: Replace the function names `min` and `max` with `math_min` and `math_max` on lines 233 & 244 of the file `src/pseudoflow/core/libhpf.c`. You should also correct the two function calls on lines 2090 and 2096. Then, `python setup.py install` should work as expected.

I'll push a fix tomorrow or this weekend.

**Comment by quic0** [comment]
Never mind. I pushed a fix in Pseudoflow `2020.6.1`.
